// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: train.proto

package train

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrainsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrainsRequest) Reset() {
	*x = TrainsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainsRequest) ProtoMessage() {}

func (x *TrainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainsRequest.ProtoReflect.Descriptor instead.
func (*TrainsRequest) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{0}
}

type TrainsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trains []string `protobuf:"bytes,1,rep,name=trains,proto3" json:"trains,omitempty"`
}

func (x *TrainsReply) Reset() {
	*x = TrainsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainsReply) ProtoMessage() {}

func (x *TrainsReply) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainsReply.ProtoReflect.Descriptor instead.
func (*TrainsReply) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{1}
}

func (x *TrainsReply) GetTrains() []string {
	if x != nil {
		return x.Trains
	}
	return nil
}

type TrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainId string `protobuf:"bytes,2,opt,name=trainId,proto3" json:"trainId,omitempty"`
	Day     int32  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Month   int32  `protobuf:"varint,4,opt,name=month,proto3" json:"month,omitempty"`
	Year    int32  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{2}
}

func (x *TrainRequest) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

func (x *TrainRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *TrainRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *TrainRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type TrainReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainId string             `protobuf:"bytes,5,opt,name=trainId,proto3" json:"trainId,omitempty"`
	Day     int32              `protobuf:"varint,6,opt,name=day,proto3" json:"day,omitempty"`
	Month   int32              `protobuf:"varint,7,opt,name=month,proto3" json:"month,omitempty"`
	Year    int32              `protobuf:"varint,8,opt,name=year,proto3" json:"year,omitempty"`
	Seats   []*TrainReply_Seat `protobuf:"bytes,9,rep,name=Seats,proto3" json:"Seats,omitempty"`
}

func (x *TrainReply) Reset() {
	*x = TrainReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainReply) ProtoMessage() {}

func (x *TrainReply) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainReply.ProtoReflect.Descriptor instead.
func (*TrainReply) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{3}
}

func (x *TrainReply) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

func (x *TrainReply) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *TrainReply) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *TrainReply) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *TrainReply) GetSeats() []*TrainReply_Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type SeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1001,opt,name=id,proto3" json:"id,omitempty"`
	UserFirstName string `protobuf:"bytes,1002,opt,name=userFirstName,proto3" json:"userFirstName,omitempty"`
	UserLastName  string `protobuf:"bytes,1003,opt,name=userLastName,proto3" json:"userLastName,omitempty"`
	UserEmail     string `protobuf:"bytes,1004,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	TrainId       string `protobuf:"bytes,1005,opt,name=trainId,proto3" json:"trainId,omitempty"`
	SeatValue     string `protobuf:"bytes,1006,opt,name=seatValue,proto3" json:"seatValue,omitempty"`
}

func (x *SeatRequest) Reset() {
	*x = SeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatRequest) ProtoMessage() {}

func (x *SeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatRequest.ProtoReflect.Descriptor instead.
func (*SeatRequest) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{4}
}

func (x *SeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SeatRequest) GetUserFirstName() string {
	if x != nil {
		return x.UserFirstName
	}
	return ""
}

func (x *SeatRequest) GetUserLastName() string {
	if x != nil {
		return x.UserLastName
	}
	return ""
}

func (x *SeatRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *SeatRequest) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

func (x *SeatRequest) GetSeatValue() string {
	if x != nil {
		return x.SeatValue
	}
	return ""
}

type SeatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string           `protobuf:"bytes,2001,opt,name=id,proto3" json:"id,omitempty"`
	Status     string           `protobuf:"bytes,2002,opt,name=status,proto3" json:"status,omitempty"`
	CustomerId string           `protobuf:"bytes,2003,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Seat       *TrainReply_Seat `protobuf:"bytes,2004,opt,name=seat,proto3" json:"seat,omitempty"`
	User       *SeatReply_User  `protobuf:"bytes,2005,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *SeatReply) Reset() {
	*x = SeatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatReply) ProtoMessage() {}

func (x *SeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatReply.ProtoReflect.Descriptor instead.
func (*SeatReply) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{5}
}

func (x *SeatReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SeatReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SeatReply) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SeatReply) GetSeat() *TrainReply_Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *SeatReply) GetUser() *SeatReply_User {
	if x != nil {
		return x.User
	}
	return nil
}

type ReceiptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,2201,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId string `protobuf:"bytes,2202,opt,name=customerId,proto3" json:"customerId,omitempty"`
	SeatId     string `protobuf:"bytes,2203,opt,name=seatId,proto3" json:"seatId,omitempty"`
}

func (x *ReceiptRequest) Reset() {
	*x = ReceiptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptRequest) ProtoMessage() {}

func (x *ReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptRequest.ProtoReflect.Descriptor instead.
func (*ReceiptRequest) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{6}
}

func (x *ReceiptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReceiptRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ReceiptRequest) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

type ReceiptReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string           `protobuf:"bytes,2305,opt,name=id,proto3" json:"id,omitempty"`
	TrainId string           `protobuf:"bytes,2306,opt,name=trainId,proto3" json:"trainId,omitempty"`
	Seat    *TrainReply_Seat `protobuf:"bytes,2307,opt,name=seat,proto3" json:"seat,omitempty"`
	From    string           `protobuf:"bytes,2308,opt,name=from,proto3" json:"from,omitempty"`
	To      string           `protobuf:"bytes,2309,opt,name=to,proto3" json:"to,omitempty"`
	Price   float32          `protobuf:"fixed32,2310,opt,name=price,proto3" json:"price,omitempty"`
	User    *SeatReply_User  `protobuf:"bytes,2311,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *ReceiptReply) Reset() {
	*x = ReceiptReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptReply) ProtoMessage() {}

func (x *ReceiptReply) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptReply.ProtoReflect.Descriptor instead.
func (*ReceiptReply) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{7}
}

func (x *ReceiptReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReceiptReply) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

func (x *ReceiptReply) GetSeat() *TrainReply_Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *ReceiptReply) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ReceiptReply) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ReceiptReply) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ReceiptReply) GetUser() *SeatReply_User {
	if x != nil {
		return x.User
	}
	return nil
}

type CancelSeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,3001,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId string `protobuf:"bytes,3002,opt,name=customerId,proto3" json:"customerId,omitempty"`
	SeatId     string `protobuf:"bytes,3003,opt,name=seatId,proto3" json:"seatId,omitempty"`
}

func (x *CancelSeatRequest) Reset() {
	*x = CancelSeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSeatRequest) ProtoMessage() {}

func (x *CancelSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSeatRequest.ProtoReflect.Descriptor instead.
func (*CancelSeatRequest) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{8}
}

func (x *CancelSeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelSeatRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CancelSeatRequest) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

type CancelSeatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,4001,opt,name=id,proto3" json:"id,omitempty"`
	Status string `protobuf:"bytes,4002,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CancelSeatReply) Reset() {
	*x = CancelSeatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelSeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSeatReply) ProtoMessage() {}

func (x *CancelSeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSeatReply.ProtoReflect.Descriptor instead.
func (*CancelSeatReply) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{9}
}

func (x *CancelSeatReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelSeatReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ChangeSeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,5001,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId string `protobuf:"bytes,5002,opt,name=customerId,proto3" json:"customerId,omitempty"`
	SourceSeat string `protobuf:"bytes,5003,opt,name=sourceSeat,proto3" json:"sourceSeat,omitempty"`
	DestSeat   string `protobuf:"bytes,5004,opt,name=destSeat,proto3" json:"destSeat,omitempty"`
}

func (x *ChangeSeatRequest) Reset() {
	*x = ChangeSeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSeatRequest) ProtoMessage() {}

func (x *ChangeSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSeatRequest.ProtoReflect.Descriptor instead.
func (*ChangeSeatRequest) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeSeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeSeatRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ChangeSeatRequest) GetSourceSeat() string {
	if x != nil {
		return x.SourceSeat
	}
	return ""
}

func (x *ChangeSeatRequest) GetDestSeat() string {
	if x != nil {
		return x.DestSeat
	}
	return ""
}

type ChangeSeatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string           `protobuf:"bytes,6001,opt,name=id,proto3" json:"id,omitempty"`
	Status     string           `protobuf:"bytes,6002,opt,name=status,proto3" json:"status,omitempty"`
	SourceSeat *TrainReply_Seat `protobuf:"bytes,6003,opt,name=sourceSeat,proto3" json:"sourceSeat,omitempty"`
	DestSeat   *TrainReply_Seat `protobuf:"bytes,6004,opt,name=destSeat,proto3" json:"destSeat,omitempty"`
}

func (x *ChangeSeatReply) Reset() {
	*x = ChangeSeatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeSeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSeatReply) ProtoMessage() {}

func (x *ChangeSeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSeatReply.ProtoReflect.Descriptor instead.
func (*ChangeSeatReply) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeSeatReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeSeatReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChangeSeatReply) GetSourceSeat() *TrainReply_Seat {
	if x != nil {
		return x.SourceSeat
	}
	return nil
}

func (x *ChangeSeatReply) GetDestSeat() *TrainReply_Seat {
	if x != nil {
		return x.DestSeat
	}
	return nil
}

type TrainReply_Seat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	Car         string `protobuf:"bytes,11,opt,name=car,proto3" json:"car,omitempty"`
	Row         int32  `protobuf:"varint,12,opt,name=row,proto3" json:"row,omitempty"`
	Position    string `protobuf:"bytes,13,opt,name=position,proto3" json:"position,omitempty"`
	Status      string `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	PassengerId string `protobuf:"bytes,15,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
}

func (x *TrainReply_Seat) Reset() {
	*x = TrainReply_Seat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainReply_Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainReply_Seat) ProtoMessage() {}

func (x *TrainReply_Seat) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainReply_Seat.ProtoReflect.Descriptor instead.
func (*TrainReply_Seat) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{3, 0}
}

func (x *TrainReply_Seat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrainReply_Seat) GetCar() string {
	if x != nil {
		return x.Car
	}
	return ""
}

func (x *TrainReply_Seat) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *TrainReply_Seat) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *TrainReply_Seat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TrainReply_Seat) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

type SeatReply_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,2301,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName    string `protobuf:"bytes,2302,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName     string `protobuf:"bytes,2303,opt,name=lastName,proto3" json:"lastName,omitempty"`
	EmailAddress string `protobuf:"bytes,2304,opt,name=emailAddress,proto3" json:"emailAddress,omitempty"`
}

func (x *SeatReply_User) Reset() {
	*x = SeatReply_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_train_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatReply_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatReply_User) ProtoMessage() {}

func (x *SeatReply_User) ProtoReflect() protoreflect.Message {
	mi := &file_train_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatReply_User.ProtoReflect.Descriptor instead.
func (*SeatReply_User) Descriptor() ([]byte, []int) {
	return file_train_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SeatReply_User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SeatReply_User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SeatReply_User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SeatReply_User) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

var File_train_proto protoreflect.FileDescriptor

var file_train_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0f, 0x0a,
	0x0d, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x25,
	0x0a, 0x0b, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x73, 0x22, 0x64, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0x9d, 0x02, 0x0a, 0x0a,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04,
	0x79, 0x65, 0x61, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72,
	0x12, 0x26, 0x0a, 0x05, 0x53, 0x65, 0x61, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x53, 0x65, 0x61,
	0x74, 0x52, 0x05, 0x53, 0x65, 0x61, 0x74, 0x73, 0x1a, 0x90, 0x01, 0x0a, 0x04, 0x53, 0x65, 0x61,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x61, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x73,
	0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x64, 0x22, 0xc3, 0x01, 0x0a, 0x0b,
	0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0f, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0xe9, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0d,
	0x75, 0x73, 0x65, 0x72, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0xea, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0xeb, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72,
	0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0xec, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x49, 0x64, 0x18, 0xed, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x09, 0x73, 0x65, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0xee, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0xa6, 0x02, 0x0a, 0x09, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x0f, 0x0a, 0x02, 0x69, 0x64, 0x18, 0xd1, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x17, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0xd2, 0x0f, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0xd3, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x73, 0x65,
	0x61, 0x74, 0x18, 0xd4, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x52, 0x04, 0x73, 0x65, 0x61,
	0x74, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0xd5, 0x0f, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x80, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x17, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0xfd, 0x11, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x09, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0xfe, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0xff, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x80, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x5b, 0x0a, 0x0e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0f, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x99, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x9a, 0x11, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x18, 0x9b, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x22, 0xc4, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0f, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x81,
	0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x07, 0x74, 0x72, 0x61,
	0x69, 0x6e, 0x49, 0x64, 0x18, 0x82, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x83, 0x12, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x53, 0x65, 0x61, 0x74, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x13, 0x0a, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x18, 0x84, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x12, 0x0f, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x85, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x6f, 0x12, 0x15, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x86, 0x12, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x87, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x5e,
	0x0a, 0x11, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0f, 0x0a, 0x02, 0x69, 0x64, 0x18, 0xb9, 0x17, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x49, 0x64, 0x18, 0xba, 0x17, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x18,
	0xbb, 0x17, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x22, 0x3b,
	0x0a, 0x0f, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x0f, 0x0a, 0x02, 0x69, 0x64, 0x18, 0xa1, 0x1f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x17, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0xa2, 0x1f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x11,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0f, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x89, 0x27, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x8a, 0x27, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x61,
	0x74, 0x18, 0x8b, 0x27, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x53, 0x65, 0x61, 0x74, 0x12, 0x1b, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x74, 0x53, 0x65, 0x61, 0x74,
	0x18, 0x8c, 0x27, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x73, 0x74, 0x53, 0x65, 0x61,
	0x74, 0x22, 0x9d, 0x01, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0f, 0x0a, 0x02, 0x69, 0x64, 0x18, 0xf1, 0x2e, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0xf2, 0x2e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x31, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x61, 0x74, 0x18, 0xf3, 0x2e,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65,
	0x61, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x74, 0x53, 0x65, 0x61, 0x74, 0x18, 0xf4,
	0x2e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x52, 0x08, 0x64, 0x65, 0x73, 0x74, 0x53, 0x65, 0x61,
	0x74, 0x32, 0xa8, 0x02, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x12,
	0x0e, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0c, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x28, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x0d, 0x2e, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x61, 0x74, 0x12, 0x0c, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x2e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x0f,
	0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0d, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x34, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x61, 0x74, 0x12, 0x12,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x61, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0a, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x53, 0x65, 0x61, 0x74, 0x12, 0x12, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x65, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06,
	0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_train_proto_rawDescOnce sync.Once
	file_train_proto_rawDescData = file_train_proto_rawDesc
)

func file_train_proto_rawDescGZIP() []byte {
	file_train_proto_rawDescOnce.Do(func() {
		file_train_proto_rawDescData = protoimpl.X.CompressGZIP(file_train_proto_rawDescData)
	})
	return file_train_proto_rawDescData
}

var file_train_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_train_proto_goTypes = []interface{}{
	(*TrainsRequest)(nil),     // 0: TrainsRequest
	(*TrainsReply)(nil),       // 1: TrainsReply
	(*TrainRequest)(nil),      // 2: TrainRequest
	(*TrainReply)(nil),        // 3: TrainReply
	(*SeatRequest)(nil),       // 4: SeatRequest
	(*SeatReply)(nil),         // 5: SeatReply
	(*ReceiptRequest)(nil),    // 6: ReceiptRequest
	(*ReceiptReply)(nil),      // 7: ReceiptReply
	(*CancelSeatRequest)(nil), // 8: CancelSeatRequest
	(*CancelSeatReply)(nil),   // 9: CancelSeatReply
	(*ChangeSeatRequest)(nil), // 10: ChangeSeatRequest
	(*ChangeSeatReply)(nil),   // 11: ChangeSeatReply
	(*TrainReply_Seat)(nil),   // 12: TrainReply.Seat
	(*SeatReply_User)(nil),    // 13: SeatReply.User
}
var file_train_proto_depIdxs = []int32{
	12, // 0: TrainReply.Seats:type_name -> TrainReply.Seat
	12, // 1: SeatReply.seat:type_name -> TrainReply.Seat
	13, // 2: SeatReply.user:type_name -> SeatReply.User
	12, // 3: ReceiptReply.seat:type_name -> TrainReply.Seat
	13, // 4: ReceiptReply.user:type_name -> SeatReply.User
	12, // 5: ChangeSeatReply.sourceSeat:type_name -> TrainReply.Seat
	12, // 6: ChangeSeatReply.destSeat:type_name -> TrainReply.Seat
	0,  // 7: TrainService.GetTrains:input_type -> TrainsRequest
	2,  // 8: TrainService.GetTrain:input_type -> TrainRequest
	4,  // 9: TrainService.GetSeat:input_type -> SeatRequest
	6,  // 10: TrainService.GetReceipt:input_type -> ReceiptRequest
	10, // 11: TrainService.ChangeSeat:input_type -> ChangeSeatRequest
	8,  // 12: TrainService.CancelSeat:input_type -> CancelSeatRequest
	1,  // 13: TrainService.GetTrains:output_type -> TrainsReply
	3,  // 14: TrainService.GetTrain:output_type -> TrainReply
	5,  // 15: TrainService.GetSeat:output_type -> SeatReply
	7,  // 16: TrainService.GetReceipt:output_type -> ReceiptReply
	11, // 17: TrainService.ChangeSeat:output_type -> ChangeSeatReply
	9,  // 18: TrainService.CancelSeat:output_type -> CancelSeatReply
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_train_proto_init() }
func file_train_proto_init() {
	if File_train_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_train_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiptReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelSeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelSeatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeSeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeSeatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainReply_Seat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_train_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatReply_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_train_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_train_proto_goTypes,
		DependencyIndexes: file_train_proto_depIdxs,
		MessageInfos:      file_train_proto_msgTypes,
	}.Build()
	File_train_proto = out.File
	file_train_proto_rawDesc = nil
	file_train_proto_goTypes = nil
	file_train_proto_depIdxs = nil
}
